config/routes.rb
Rails.application.routes.draw do
  

  resources :visits
  resources :doctors
  root 'static_pages#home'
  get  '/help',   to: 'static_pages#help'
  get  '/about',   to: 'static_pages#about'
  get  '/patients',  to: 'patients#index'
  get  '/harmonogram',  to: 'visits#index'
  get '/patients/new', to:  'patients#new'
  post '/patients', to: 'patients#create'
  get '/patients/:id', to: 'patients#show'
  get 'patients/:id/edit', to: 'patients#edit'
  patch "patients/:id" => "patients#update"
  delete "patients/:id" => "patients#destroy"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/doctor.rb
class Doctor < ApplicationRecord
    validates :doctor_name, presence: true
    validates :doctor_lname, presence: true
    validates :spec, presence: true
   
    has_many :visits
    has_many :patients, :through =>  :visits
    
  
end

app/models/patient.rb
class Patient < ApplicationRecord
      validates :name, presence: true
      validates :lname, presence: true
      validates :pesel, presence: true
      validates :dob, presence: true
  has_many :visits, dependent: :delete_all
  has_many :doctors, :through => :visits
end

app/models/visit.rb
class Visit < ApplicationRecord
  belongs_to :patient, :dependent => :delete
  belongs_to :doctor, :dependent => :delete
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/doctors_controller.rb
class DoctorsController < ApplicationController
  before_action :set_doctor, only: [:show, :edit, :update, :destroy]

  # GET /doctors
  # GET /doctors.json
  def index
    @doctors = Doctor.all
  end

  # GET /doctors/1
  # GET /doctors/1.json
  def show
  end

  # GET /doctors/new
  def new
    @doctor = Doctor.new
  end

  # GET /doctors/1/edit
  def edit
  end

  # POST /doctors
  # POST /doctors.json
  def create
    @doctor = Doctor.new(doctor_params)

    respond_to do |format|
      if @doctor.save
        format.html { redirect_to @doctor, notice: 'Dodano nowego lekarza do bazy.' }
        format.json { render :show, status: :created, location: @doctor }
      else
        format.html { render :new }
        format.json { render json: @doctor.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /doctors/1
  # PATCH/PUT /doctors/1.json
  def update
    respond_to do |format|
      if @doctor.update(doctor_params)
        format.html { redirect_to @doctor, notice: 'Dane lekarza zmieniono pomyślnie.' }
        format.json { render :show, status: :ok, location: @doctor }
      else
        format.html { render :edit }
        format.json { render json: @doctor.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /doctors/1
  # DELETE /doctors/1.json
  def destroy
    @doctor.destroy
    respond_to do |format|
      format.html { redirect_to doctors_url, notice: 'Usunięto lekarza z bazy.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_doctor
      @doctor = Doctor.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def doctor_params
      params.require(:doctor).permit(:doctor_name, :doctor_lname, :spec)
    end
end

app/controllers/pacjenci_controller.rb
class PacjenciController < ApplicationController
  def new
  end
end

app/controllers/patients_controller.rb
class PatientsController < ApplicationController
     
  def new
  end
  
    helper_method :sort_column, :sort_direction
    def index
         @patients = Patient.order(sort_column + " " + sort_direction)
    end
 def create
     
     patient = Patient.new(patient_params)
        
        if patient.save
            redirect_to "/patients"
        else
            flash[:errors] = patient.errors.full_messages
            redirect_to "/patients/new"
        end
 end
     def show
        @patient = Patient.find(params[:id])
     end
     
     def edit
           @patient = Patient.find(params[:id])
     end
      def update
        patient = Patient.find(params[:id])
        if patient.update(patient_params)
            redirect_to "/patients"
        else
            flash[:errors] = patient.errors.full_messages
            redirect_to "/patients/#{patient.id}/edit"
        end
      end
     
     def destroy 
         patient = Patient.find(params[:id])
         patient.destroy
         redirect_to "/patients#index"
     end
 
   def patient_params
    params.require(:patient).permit(:name, :lname, :pesel, :tel, :dob)
   end
   
   private
   def sort_column
       Patient.column_names.include?(params[:sort]) ? params[:sort] : "name"
   end
   
   def sort_direction
       %w[asc desc].include?(params[:direction]) ? params[:direction] : "asc"
   end
   
end
  

 

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def help
  end
  
  def about
  end
end

app/controllers/visits_controller.rb
class VisitsController < ApplicationController
  before_action :set_visit, only: [:show, :edit, :update, :destroy]

  # GET /visits
  # GET /visits.json
  def index
    @visits = Visit.all
  end

  # GET /visits/1
  # GET /visits/1.json
  def show
  end

  # GET /visits/new
  def new
    @visit = Visit.new
  end

  # GET /visits/1/edit
  def edit
  end

  # POST /visits
  # POST /visits.json
  def create
    @visit = Visit.new(visit_params)

    respond_to do |format|
      if @visit.save
        format.html { redirect_to @visit, notice: 'Dodano nową wizytę.' }
        format.json { render :show, status: :created, location: @visit }
      else
        format.html { render :new }
        format.json { render json: @visit.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /visits/1
  # PATCH/PUT /visits/1.json
  def update
    respond_to do |format|
      if @visit.update(visit_params)
        format.html { redirect_to @visit, notice: 'Wizyta edytowana pomyślnie.' }
        format.json { render :show, status: :ok, location: @visit }
      else
        format.html { render :edit }
        format.json { render json: @visit.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /visits/1
  # DELETE /visits/1.json
  def destroy
    @visit.destroy
    respond_to do |format|
      format.html { redirect_to visits_url, notice: 'Wizyta usunięta.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_visit
      @visit = Visit.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def visit_params
      params.require(:visit).permit(:start_date, :end_date, :patient_id, :doctor_id)
    end
end

app/controllers/wizyty_controller.rb
class WizytyController < ApplicationController
  def new
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
    
    def sortable(column, title = nil)
        title ||= column.titleize
        direction = column == sort_column && sort_direction == "asc" ? "desc" : "asc"
        link_to title, :sort => column, :direction => direction
    end
end

app/helpers/doctors_helper.rb
module DoctorsHelper
end

app/helpers/pacjenci_helper.rb
module PacjenciHelper
end

app/helpers/patients_helper.rb
module PatientsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/visits_helper.rb
module VisitsHelper
end

app/helpers/wizyty_helper.rb
module WizytyHelper
end

app/views/doctors/_form.html.erb
<%= simple_form_for(@doctor) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :doctor_name %>
    <%= f.input :doctor_lname %>
    <%= f.input :spec %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/doctors/edit.html.erb
<h1>Editing Doctor</h1>

<%= render 'form', doctor: @doctor %>

<%= link_to 'Show', @doctor %> |
<%= link_to 'Back', doctors_path %>

app/views/doctors/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Lekarze</h1>
<center>
<table class="tg" >
  <thead>
    <tr>
      <th>Imię </th>
      <th>Nazwisko</th>
      <th>Specjalizacja</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @doctors.each do |doctor| %>
      <tr>
        <td><%= doctor.doctor_name %></td>
        <td><%= doctor.doctor_lname %></td>
        <td><%= doctor.spec %></td>
        <td><%= link_to 'Pokaż', doctor %></td>
        <td><%= link_to 'Edytuj', edit_doctor_path(doctor) %></td>
        <td><%= link_to 'Usuń', doctor, method: :delete, data: { confirm: 'Czy jesteś pewny?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
</center>
<br>

<%= link_to 'New Doctor', new_doctor_path %>

app/views/doctors/new.html.erb
<h1>New Doctor</h1>

<%= render 'form', doctor: @doctor %>

<%= link_to 'Back', doctors_path %>

app/views/doctors/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Doctor name:</strong>
  <%= @doctor.doctor_name %>
</p>

<p>
  <strong>Doctor lname:</strong>
  <%= @doctor.doctor_lname %>
</p>

<p>
  <strong>Spec:</strong>
  <%= @doctor.spec %>
</p>

<%= link_to 'Edit', edit_doctor_path(@doctor) %> |
<%= link_to 'Back', doctors_path %>

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    by Ola & Adam
  </small>
  <nav>
    <ul>
      <li><%= link_to "O programie",   about_path %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "Telm App", root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Strona główna",   root_path %></li>
        <li><%= link_to "Pomoc",   help_path %></li>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_rails_default.html.erb
<%= csrf_meta_tags %>
<%= stylesheet_link_tag    'application', media: 'all',
                                          'data-turbolinks-track': 'reload' %>
<%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield(:title) %> | TELM App</title>
    <%= render 'layouts/rails_default' %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <%= yield %>
      <%= render 'layouts/footer' %>
    </div>
  </body>
</html>

app/views/patients/_form.html.erb
<%= form_for(@patient) do |f| %>
  <% if @patient.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@patient.errors.count, "error") %> prohibited this patient from being saved:</h2>

      <ul>
      <% @patient.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :lname %><br>
    <%= f.text_field :lname %>
  </div>
  <div class="field">
    <%= f.label :pesel %><br>
    <%= f.number_field :pesel %>
  </div>
  <div class="field">
    <%= f.label :dob %><br>
    <%= f.date_select :dob %>
  </div>
  <div class="field">
    <%= f.label :tel %><br>
    <%= f.text_field :tel %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/patients/edit.html.erb
<link href='http://fonts.googleapis.com/css?family=Open+Sans+Condensed:300' rel='stylesheet' type='text/css'>
<style type="text/css">
.form-style-8{
    font-family: 'Open Sans Condensed', arial, sans;
    width: 500px;
    padding: 30px;
    background: #FFFFFF;
    margin: 50px auto;
    box-shadow: 0px 0px 15px rgba(0, 0, 0, 0.22);
    -moz-box-shadow: 0px 0px 15px rgba(0, 0, 0, 0.22);
    -webkit-box-shadow:  0px 0px 15px rgba(0, 0, 0, 0.22);

}
.form-style-8 h2{
    background: #4D4D4D;
    text-transform: uppercase;
    font-family: 'Open Sans Condensed', sans-serif;
    color: #797979;
    font-size: 18px;
    font-weight: 100;
    padding: 20px;
    margin: -30px -30px 30px -30px;
}
.form-style-8 input[type="text"],
.form-style-8 input[type="date"],
.form-style-8 input[type="datetime"],
.form-style-8 input[type="email"],
.form-style-8 input[type="number"],
.form-style-8 input[type="search"],
.form-style-8 input[type="time"],
.form-style-8 input[type="url"],
.form-style-8 input[type="password"],
.form-style-8 textarea,
.form-style-8 select 
{
    box-sizing: border-box;
    -webkit-box-sizing: border-box;
    -moz-box-sizing: border-box;
    outline: none;
    display: block;
    width: 100%;
    padding: 7px;
    border: none;
    border-bottom: 1px solid #ddd;
    background: transparent;
    margin-bottom: 10px;
    font: 16px Arial, Helvetica, sans-serif;
    height: 45px;
}
.form-style-8 textarea{
    resize:none;
    overflow: hidden;
}
.form-style-8 input[type="button"], 
.form-style-8 input[type="submit"]{
    -moz-box-shadow: inset 0px 1px 0px 0px #45D6D6;
    -webkit-box-shadow: inset 0px 1px 0px 0px #45D6D6;
    box-shadow: inset 0px 1px 0px 0px #45D6D6;
    background-color: #2CBBBB;
    border: 1px solid #27A0A0;
    display: inline-block;
    cursor: pointer;
    color: #FFFFFF;
    font-family: 'Open Sans Condensed', sans-serif;
    font-size: 14px;
    padding: 8px 18px;
    text-decoration: none;
    text-transform: uppercase;
}
.form-style-8 input[type="button"]:hover, 
.form-style-8 input[type="submit"]:hover {
    background:linear-gradient(to bottom, #34CACA 5%, #30C9C9 100%);
    background-color:#34CACA;
}
</style>
<script type="text/javascript">
//auto expand textarea
function adjust_textarea(h) {
    h.style.height = "20px";
    h.style.height = (h.scrollHeight)+"px";
}
</script>

<h1>Edycja danych pacjenta: <%= @patient.name %> <%= @patient.lname %> </h1>
 <div class="form-style-8">
        <% if flash[:errors] %>
        <% flash[:errors].each do |e| %>
        <p> <%= e %></p>
        <% end %>
        <% end %>
     <br>
 <h2>Edytuj dane pacjenta</h2>
  <form action="/patients/<%= @patient.id %>" method="post">
  <input type="hidden" name="_method" value="patch">
    <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
        <p>  
        <label> Imię </label>
        <input type="text" name="patient[name]"  value="<%= @patient.name %>" /> 
        </p>
     <p> 
     <label> Nazwisko </label>
     <input type="text" name="patient[lname]" value="<%= @patient.lname %>" />
     </p>
   <p>  
   <label> Numer PESEL </label>
   <input type="number" name="patient[pesel]" value="<%= @patient.pesel %>" />   
   </p>
    <p> 
    <label> Data Urodzenia </label>
    <input type="number" name="patient[dob]"  value="<%= @patient.dob %>"  />  
    </p>
     <p> 
     <label> Telefon Kontaktowy </label>
     <input type="tel" name="patient[tel]"  value="<%= @patient.tel %>" /> 
     </p>
     <center>
      <p>  <input type="submit" name="Dodaj do bazy" value="Zmień dane w bazie" class="btn btn-lg btn-primary"/>  </p>
      </center>
  </form>
</div>
</form>



<center>
<a href="/patients" class="btn btn-lg btn-primary"> Powrót </a>
</center>

app/views/patients/index.html.erb
<% provide(:title, 'Pacjenci') %>

<h1>Lista pacjentów</h1>

<p>  </p>
<center>
    <a href="/patients/new" class="btn btn-lg btn-primary">Dodaj Pacjenta</a>
    </center>
    <p></p>
    
    <center>
<table class="tg">
    <thread>
        <tr>
            <th><%= sortable "name","Imię" %> </th>
            <th><%= sortable "lname","Nazwisko" %></th>
            <th>Pesel</th>
            <th>Telefon</th>
            <th>Funkcje</th>
        </tr>
        <tbody>
            <% @patients.each do |patient| %>
            
            <tr>
                <td><%= patient.name %> </td>
                <td> <%= patient.lname %>  </td>
                <td><%= patient.pesel %></td>
                <td> <%= patient.tel %>    </td>
                <td><a href="/patients/<%= patient.id %>"> Pokaż profil </a></td>
                <td><a href="/patients/<%= patient.id %>/edit"> Edytuj profil </a></td>
                <td><a href="/patients/<%= patient.id %>" data-method="delete" data-confirm="Czy jesteś pewny?">Usuń Profil </a></td>
             </tr>
        <%end %>
            
        </tbody>
    </thread>
</table>
<p></p>
<a href="/patients/new" class="btn btn-lg btn-primary">Dodaj Pacjenta</a>
</center>

app/views/patients/new.html.erb
<script type="text/javascript">
//auto expand textarea
function adjust_textarea(h) {
    h.style.height = "20px";
    h.style.height = (h.scrollHeight)+"px";
}
</script>

<% provide(:title, 'Dodaj pacjenta') %>
 
        

<h1>Dodaj pacjenta</h1>

    <div class="form-style-8">
        <% if flash[:errors] %>
        <% flash[:errors].each do |e| %>
        <p> <%= e %></p>
        <% end %>
        <% end %>
     <br>
    
        
  <h2>Wprowadź dane pacjenta</h2>
  <form action="/patients" method="post">
  
    <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
        <p>  
        <label> Imię </label>
        <input type="text" name="patient[name]" placeholder="Imię" /> 
        </p>
     <p> 
     <label> Nazwisko </label>
     <input type="text" name="patient[lname]" placeholder="Nazwisko" />
     </p>
   <p>  
   <label> Numer PESEL </label>
   <input type="number" name="patient[pesel]" placeholder="Pesel" />   
   </p>
    <p> 
    <label> Data Urodzenia </label>
    <input type="date" name="patient[dob]" placeholder="Data Urodzenia" />  
    </p>
     <p> 
     <label> Telefon Kontaktowy </label>
     <input type="tel" name="patient[tel]" placeholder="Numer Telefonu"/> 
     </p>
      <p>  <input type="submit" name="Dodaj do bazy" value="Dodaj do bazy" class="btn btn-lg btn-primary"/>  </p>
  </form>
</div>
</form>

app/views/patients/show.html.erb
<style type="text/css">
.tg  {border-collapse:collapse;border-spacing:0;border-color:#ccc;}
.tg td{font-family:Arial, sans-serif;font-size:14px;padding:10px 5px;border-style:solid;border-width:0px;overflow:hidden;word-break:normal;border-color:#ccc;color:#333;background-color:#fff;border-top-width:1px;border-bottom-width:1px;}
.tg th{font-family:Arial, sans-serif;font-size:14px;font-weight:normal;padding:10px 5px;border-style:solid;border-width:0px;overflow:hidden;word-break:normal;border-color:#ccc;color:#333;background-color:#f0f0f0;border-top-width:1px;border-bottom-width:1px;}
.tg .tg-yw4l{vertical-align:top}
</style>

<h1>Pacjent <%= @patient.name %> <%= @patient.lname %> - dane</h1>

<table class="tg">
    <thead>
        <tr>
            <td>Imię</td>
            <td>Nazwisko</td>
            <td>Pesel</td>
            <td>Telefon</td>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td><%= @patient.name %> </td>
            <td><%= @patient.lname %> </td>
            <td><%= @patient.pesel%> </td>
            <td><%= @patient.tel %> </td>
        </tr>
    </tbody>
</table>

<a href="/patients" class="btn btn-lg btn-primary"> Powrót </a>

app/views/static_pages/about.html.erb
<% provide(:title, "O programie") %>
<h1>O programie</h1>
<p>
Zasady zaliczenia 
    <a href="http://telm.ire.pw.edu.pl/data/_uploaded/file/ZasadyZaliczeniaTELM2017.pdf">TELMu.</a>
</p>

app/views/static_pages/help.html.erb
<% provide(:title, "Pomoc") %>
<h1>Pomoc</h1>
<p>
Instrukcja dla użytkownika (przekleję z dokumentacji).
</p>

app/views/static_pages/home.html.erb
<div class="center jumbotron">
  <h1>NZOZ w Skowronkowie Dolnym</h1>

  <h2>
    Rejestracja i Zapisy Pacjentów
  </h2>

  <%= link_to "Pacjenci", patients_path, class: "btn btn-success btn-lg btn-block" %>
  <br>
  <%= link_to "Harmonogram wizyt", harmonogram_path, class: "btn btn-lg btn-block btn-success" %>
</div>
<%= image_tag("eskulap.png", size: "150x102", alt: "Home logo")%>

app/views/visits/_form.html.erb
<%= simple_form_for(@visit) do |f| %>
  <%= f.error_notification %>

 <div class="form-style-8">
    <%= f.input :start_date %>
    <%= f.input :end_date %>
    <%= f.association :patient, label_method: "#{:lname}" %>
    <%= f.association :doctor, label_method: "#{:doctor_lname}"  %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/visits/edit.html.erb
<h1>Edytuj wizytę</h1>

<%= render 'form', visit: @visit %>

<%= link_to 'Pokaż', @visit %> |
<%= link_to 'Cofnij', visits_path %>

app/views/visits/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Wizyty</h1>
<center>
<table class="tg">
  <thead>
    <tr>
      <th>Początek wizyty</th>
      <th>Koniec wizyty</th>
      <th>Imię Pacjenta</th>
      <th>Nazwisko Pacjenta</th>
      <th>Imię Lekarza</th>
      <th>Nazwisko Lekarza</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @visits.each do |visit| %>
      <tr>
        <td><%= visit.start_date %></td>
        <td><%= visit.end_date %></td>
        <td><%= visit.patient.name %></td>
        <td><%= visit.patient.lname %></td>
        <td><%= visit.doctor.doctor_name %></td>
        <td><%= visit.doctor.doctor_lname %></td>
        <td><%= link_to 'Pokaż', visit %></td>
        <td><%= link_to 'Edytuj', edit_visit_path(visit) %></td>
        <td><%= link_to 'Usuń', visit, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
</center>
<br>

<%= link_to 'Dodaj nową wizytę', new_visit_path %>

app/views/visits/new.html.erb
<h1>Nowa wizyta</h1>

<%= render 'form', visit: @visit %>

<%= link_to 'Cofnij', visits_path %>

app/views/visits/show.html.erb
<p id="notice"><%= notice %></p>


<table class="tg">
    <thead>
        <tr>
            <td>Start date:</td>
            <td>End date</td>
            <td>Patient Last name</td>
            <td>Patient first name</td>
            <td>Doctor Last name</td>
            <td>Doctor first name</td>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td><%= @visit.start_date %> </td>
            <td><%= @visit.end_date %> </td>
            <td><%= @visit.patient.lname %> </td>
            <td><%= @visit.patient.name%> </td>
            <td><%=  @visit.doctor.doctor_lname %> </td>
           <td><%=  @visit.doctor.doctor_name %> </td>
    </tbody>
</table>




<%= link_to 'Edytuj', edit_visit_path(@visit) %> |
<%= link_to 'Cofnij', visits_path %>